// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {ReceiptEscrow} from "../src/ReceiptEscrow.sol";

/**
 * Cross-language pin for the EIP-712 payload.
 *
 * The buyer signs in TypeScript (viem) and the escrow recovers in Solidity.
 * If the struct field order, a field name, a type, or the domain drifts on one
 * side, signatures stop recovering and the failure shows up as a confusing
 * "BadSignature" during a live paid request. Both sides are pinned here to one
 * committed fixture instead: test/fixtures/eip712.json, generated by viem and
 * asserted by the TypeScript suite as well.
 */
contract Eip712InteropTest is Test {
    address constant FIXED = 0x3333333333333333333333333333333333333333;

    function test_digestMatchesTheTypeScriptFixture() public {
        string memory json = vm.readFile("./test/fixtures/eip712.json");

        uint256 chainId = vm.parseJsonUint(json, ".chainId");
        bytes32 expectedDigest = vm.parseJsonBytes32(json, ".digest");
        bytes32 expectedTypeHash = vm.parseJsonBytes32(json, ".typeHash");
        bytes32 termsHash = vm.parseJsonBytes32(json, ".termsHash");
        address payer = vm.parseJsonAddress(json, ".payer");
        address payee = vm.parseJsonAddress(json, ".payee");
        uint256 amount = vm.parseJsonUint(json, ".amount");
        uint64 deadline = uint64(vm.parseJsonUint(json, ".deadline"));
        bytes32 nonce = vm.parseJsonBytes32(json, ".nonce");
        assertEq(vm.parseJsonAddress(json, ".verifyingContract"), FIXED, "fixture address drifted");

        // The domain binds chainId and address(this), so place the code at the
        // address the fixture was generated against, on that chain id.
        vm.chainId(chainId);
        ReceiptEscrow deployed = new ReceiptEscrow(address(0xAD1), 1e10);
        vm.etch(FIXED, address(deployed).code);
        ReceiptEscrow escrow = ReceiptEscrow(FIXED);

        assertEq(escrow.termsTypeHash(), expectedTypeHash, "Terms type hash differs from TypeScript");
        assertEq(
            escrow.termsDigest(termsHash, payer, payee, amount, deadline, nonce),
            expectedDigest,
            "EIP-712 digest differs from TypeScript"
        );
    }
}
